### ISSUE TITLE
Undo doesn't undo the operation, only individual components of it.

### ISSUE THREAD

**Issue by psilord** [RyanBurnside/divide-thirds#1]
After using the script, which might say add 9 guide lines, I have to undo 9 times to get back to the state before the script was run.

Maybe you can consider using an undo group, like using `gimp-undo-push-group-start` and `gimp-undo-push-group-end`.

Thank you!

**Comment by RyanBurnside** [comment]
Should be fixed now. :)
Please verify at your leisure.

**Comment by psilord** [comment]
Seems to work. Thank you!
